// assets.js
export const defaultCRMData = [
  { id: 1, name: "Winford Asher", topic: "Cafe A100", status: "New", created: "4/2/2024" },
  { id: 2, name: "Josia Love", topic: "Upgrading service plan", status: "In Progress", created: "3/30/2024" },
  { id: 3, name: "Caden West", topic: "Website Design", status: "Completed", created: "5/1/2024" },
  { id: 4, name: "Emily Brooks", topic: "SEO Optimization", status: "New", created: "6/15/2024" },
  { id: 5, name: "Liam Taylor", topic: "Digital Marketing Strategy", status: "In Progress", created: "6/10/2024" },
  { id: 6, name: "Megan Collins", topic: "UI/UX Redesign", status: "Completed", created: "5/12/2024" },
  { id: 7, name: "Noah Harris", topic: "Mobile App Development", status: "New", created: "7/3/2024" },
  { id: 8, name: "Isabella Young", topic: "Content Writing", status: "In Progress", created: "7/25/2024" },
  { id: 9, name: "Aiden Scott", topic: "Brand Strategy", status: "Completed", created: "5/22/2024" },
  { id: 10, name: "Sophia Green", topic: "Market Research", status: "New", created: "8/1/2024" },
  { id: 11, name: "Jackson Lee", topic: "Product Launch", status: "In Progress", created: "7/30/2024" },
  { id: 12, name: "Olivia Martinez", topic: "Customer Support", status: "Completed", created: "6/18/2024" },
  { id: 13, name: "Ethan Gonzalez", topic: "E-commerce Integration", status: "New", created: "7/8/2024" },
  { id: 14, name: "Charlotte Perez", topic: "Event Planning", status: "In Progress", created: "5/5/2024" },
  { id: 15, name: "Liam Carter", topic: "Data Analysis", status: "Completed", created: "6/20/2024" },
  { id: 16, name: "Amelia Cooper", topic: "Social Media Campaign", status: "New", created: "7/15/2024" },
  { id: 17, name: "Mason Walker", topic: "Video Production", status: "In Progress", created: "8/10/2024" },
  { id: 18, name: "Ella Robinson", topic: "Graphic Design", status: "Completed", created: "5/25/2024" },
  { id: 19, name: "Benjamin King", topic: "Customer Retention", status: "New", created: "6/3/2024" },
  { id: 20, name: "Chloe Wright", topic: "App Update", status: "In Progress", created: "7/22/2024" },
  { id: 21, name: "James King", topic: "Performance Marketing", status: "Completed", created: "6/8/2024" },
  { id: 22, name: "Zoe Adams", topic: "Partnerships", status: "New", created: "8/5/2024" },
  { id: 23, name: "Lucas Nelson", topic: "Data Visualization", status: "In Progress", created: "7/18/2024" },
  { id: 24, name: "Lily Mitchell", topic: "Sales Automation", status: "Completed", created: "6/28/2024" },
  { id: 25, name: "Henry Carter", topic: "Automation Tools", status: "New", created: "7/12/2024" },
];
